function createfigure_temp_tax(X1, Y1, Y2, Y3)
global tax_exper

%CREATEFIGURE(X1, Y1, Y2, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  
%  Auto-generated by MATLAB on 13-Oct-2022 20:23:55

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',3);

% Create title
title('G');

hold(subplot1,'off');
% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y2,'Parent',subplot2,'LineWidth',3);

% Create title
title('Tax Capital');

hold(subplot2,'off');

% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X1,Y3,'Parent',subplot3,'LineWidth',3);

% Create title
title('Tax Labor');

hold(subplot3,'off');




