function createfigure_temp_tax(X1, Y1, Y2, Y3,Y4)
global tax_exper

%CREATEFIGURE(X1, Y1, Y2, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 13-Oct-2022 20:23:55

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',3);

% Create title
title('Wages');

hold(subplot1,'off');
% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y2,'Parent',subplot2,'LineWidth',3);

% Create title
title('Labor');

hold(subplot2,'off');
% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X1,Y3,'Parent',subplot3,'LineWidth',3);

% Create title
title('Interest Rate');

hold(subplot3,'off');

% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create plot
plot(X1,Y4,'Parent',subplot4,'LineWidth',3);

% Create title
title('Investment');

hold(subplot4,'off');

